config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"
    get "/help", to: "static_pages#help"
    get "/about", to: "static_pages#about"
    get "/contact", to: "static_pages#contact"
    get "/signup", to: "users#new"
    post "/signup", to: "users#create"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    resources :users do
      member do
        get :following, :followers
      end
    end
    resources :account_activations, only: :edit
    resources :password_resets, except: %i(index show destroy)
    resources :microposts, only: %i(create destroy)
    resources :relationships, only: %i(create destroy)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    return unless logged_in?

    @micropost = current_user.microposts.build
    @pagy, @feed_items = pagy current_user.feed.newest, items: Settings.page_10
  end

  def help; end

  def about; end

  def contact; end
end

app/views/static_pages/about.html.erb
<% provide :title, I18n.t("layouts.about") %>
<h1><%= t ".heading" %></h1>
<p><%= t ".paragraph_html", source: Settings.servers.tutorials %></p>

app/views/static_pages/contact.html.erb
<% provide :title, I18n.t("layouts.contact") %>
<h1><%= t ".heading" %></h1>
<p><%= t ".paragraph_html", source: Settings.servers.contact %></p>

app/views/static_pages/help.html.erb
<% provide :title, I18n.t("layouts.help") %>
<h1><%= t ".heading" %></h1>
<p><%= t ".paragraph_html", source: Settings.servers.help %></p>

app/views/static_pages/home.html.erb
<% provide :title,  I18n.t("layouts.home") %>
<% if logged_in? %>
 <div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <%= render "shared/user_info" %>
    </section>
    <section class="stats">
      <%= render "shared/stats" %>
    </section>
    <section class="micropost_form">
      <%= render "shared/micropost_form" %>
    </section>
  </aside>
  <div class="col-md-8">
    <h3><%= t ".feed" %></h3>
    <%= render "shared/feed" %>
  </div>
</div>
<% else %>
  <h1><%= t "layouts.sample_app" %></h1>
  <p><%= t ".paragraph_html", source: Settings.servers.tutorials %></p>
  <div class="center jumbotron">
    <h1><%= t ".heading" %></h1>
    <h2><%= t ".paragraph_html", source: Settings.servers.tutorials %></h2>
    <%= link_to t(".sign_up"), signup_path, class: "btn btn-lg btn-primary" %>
  </div>

  <%= link_to image_tag("rails.svg", width: "200"), Settings.servers.rails, class: "image-link" %>
  <%= link_to image_tag("kitten.jpg", width: "200"), "#", class: "image-link kitten" %>
<% end %>