config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"
    get "/help", to: "static_pages#help"
    get "/about", to: "static_pages#about"
    get "/contact", to: "static_pages#contact"
    get "/signup", to: "users#new"
    post "/signup", to: "users#create"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    resources :users do
      member do
        get :following, :followers
      end
    end
    resources :account_activations, only: :edit
    resources :password_resets, except: %i(index show destroy)
    resources :microposts, only: %i(create destroy)
    resources :relationships, only: %i(create destroy)
  end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  before_action :load_user, :valid_user, :check_expiration,
                only: %i(edit update)

  def new; end

  def edit; end

  def create
    @user = User.find_by email: params[:password_reset][:email]&.downcase
    if @user
      @user.create_reset_digest
      @user.send_password_reset_email
      flash[:info] = t "password_resets.create.email_sent"
      redirect_to root_path
    else
      flash.now[:danger] = t "password_resets.create.email_not_found"
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if user_params[:password].empty?
      @user.errors.add :password, t("password_resets.update.password_empty")
      render :edit, status: :unprocessable_entity
    elsif @user.update user_params
      log_in @user
      @user.update_column :reset_digest, nil
      flash[:success] = t "password_resets.update.password_reset"
      redirect_to @user
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit User::RESET_PASSWORD_ATTRIBUTES
  end

  def load_user
    @user = User.find_by email: params[:email]
    return if @user

    flash[:danger] = t "password_resets.edit.user_not_found"
    redirect_to root_url
  end

  def valid_user
    return if @user.activated? && @user.authenticated?(:reset, params[:id])

    flash[:danger] = t "password_resets.edit.invalid_user"
    redirect_to root_url
  end

  def check_expiration
    return unless @user.password_reset_expired?

    flash[:danger] = t "password_resets.edit.expired"
    redirect_to new_password_reset_url
  end
end

app/views/password_resets/edit.html.erb
<% provide :title, I18n.t("password_resets.edit.heading") %>
<h1><%= t ".heading" %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @user, url: password_reset_path(params[:id]) do |f| %>
      <%= render "shared/error_messages" %>
      <%= hidden_field_tag :email, @user.email %>
      <%= f.label :password, t(".new_password") %>
      <%= f.password_field :password, class: "form-control" %>
      <%= f.label :password_confirmation, t(".confirmation") %>
      <%= f.password_field :password_confirmation, class: "form-control" %>
      <%= f.submit t(".submit"), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/password_resets/new.html.erb
<% provide :title, I18n.t("password_resets.new.forgot_password") %>
<h1><%= t ".forgot_password" %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for :password_reset, url: password_resets_path do |f| %>
      <%= f.label :email, t(".email") %>
      <%= f.email_field :email, class: "form-control" %>
      <%= f.submit t(".submit"), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>