config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"
    get "/help", to: "static_pages#help"
    get "/about", to: "static_pages#about"
    get "/contact", to: "static_pages#contact"
    get "/signup", to: "users#new"
    post "/signup", to: "users#create"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    resources :users do
      member do
        get :following, :followers
      end
    end
    resources :account_activations, only: :edit
    resources :password_resets, except: %i(index show destroy)
    resources :microposts, only: %i(create destroy)
    resources :relationships, only: %i(create destroy)
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to t("layouts.about"), about_path %></li>
      <li><%= link_to t("layouts.contact"), contact_path %></li>
      <li><%= link_to t("layouts.news"), Settings.servers.news %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to t("layouts.sample_app"), root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t("layouts.home"), root_path %></li>
        <li><%= link_to t("layouts.help"), help_path %></li>
        <li><%= link_to t("layouts.english"), locale: :en %></li>
        <li><%= link_to t("layouts.vietnamese"), locale: :vi %></li>
        <% if logged_in? %>
          <li><%= link_to t("layouts.users"), users_path %></li>
          <li class="dropdown">
            <%= link_to "#", id: "account", class: "dropdown-toggle", data: { toggle: "dropdown" } do %>
              <%= t "layouts.account" %>
              <b class="caret"></b>
            <% end %>
            <ul id="dropdown-menu" class="dropdown-menu">
              <li><%= link_to t("layouts.profile"), current_user %></li>
              <li><%= link_to t("layouts.settings"), edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li><%= link_to t("layouts.logout"), logout_path, data: { "turbo-method": :delete } %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t("layouts.login"), login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield :title %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag "i18n" %>
    <%= javascript_include_tag "translations", skip_pipeline: true %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render "layouts/footer" %>
      <script type="text/javascript">
        I18n.defaultLocale = "<%= I18n.default_locale %>";
        I18n.locale = "<%= I18n.locale %>";
      </script>
    </div>
  </body>
</html>